version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a Python version: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local on arm64/Apple Silicon.
        VARIANT: '3.10-bullseye'
        # Options
        NODE_VERSION: '14'
    volumes:
      - ..:/workspace:cached
      # Docker volume to contain node_modules for performance reason
      - frontend-node_modules:/workspace/frontend/node_modules
      # Docker
      - ~/.docker:/root/.docker:z
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      - ~/.ssh:/root/.ssh:z
      # For Windows without WSL, a copy will be made
      # from /tmp/.ssh to ~/.ssh to fix permissions
      # - ~/.ssh:/tmp/.ssh:ro
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history:z
      # Git config
      - ~/.gitconfig:/root/.gitconfig:z
      # Kubernetes
      # - ~/.kube:/root/.kube:z

      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode

  # to conect inside containers use the db (service name) as host
  # docker automaticaly create a network foreach service with service
  # name as host, this host name docker resolve to the real assigned
  # ip by docker

volumes:
  frontend-node_modules:
# secrets:
#   mongo-root-passwd:
#     file: ./secrets/mongo-root-passwd
#   mongo-user-passwd:
#     file: ./secrets/mongo-user-passwd
