name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Arevalo-Edgar14/IA2
        TARGET_BRANCH: master
        BUILD_SCRIPT: cd frontend && yarn && yarn build
        BUILD_DIR: blog/.vuepress/dist/
